stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: pwd
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: csuliuming/abc
timeout: 60
notification: {}
